### ISSUE TITLE
Article：read_state从bool值改为字符串类型

### ISSUE THREAD

**Issue by yzy11235** [MinJieDev/Roadmap-Backend#69]
`read_state`从已读、未读两个状态，更改为已读、在看、未读三个状态，分别对应三个字符串：
- `read`
- `reading`
- `unread`

同理essay的state可以改成字符串类型，不过这个可改可不改

**Comment by debug-zhang** [comment]
`Article`  的  `read_state`  修改为字符串映射，固定为三种类型 U、I、F：
read_state = models.CharField(max_length=1, choices=READ_STATE_CHOICES, default='U')
READ_STATE_CHOICES = (('U', 'unread'), ('I', 'reading'), ('F', 'read'))

`Essay` 同理：
state = models.CharField(max_length=1, choices=STATE_CHOICES, default='U')
STATE_CHOICES = (('U', 'unfinished'), ('I', 'writing'), ('F', 'finished'))
